export enum ENVIRONMENTS {
  PRODUCTION = "production",
  DEVELOPMENT = "development",
}

export enum MODEL_NAMES {
  ADMINS = "admins",
  CONVERSATIONS = "conversations",
  ELEMENTS = "elements",
  MESSAGES = "messages",
  NOTIFICATIONS = "notifications",
  PAYMENT_ACCOUNTS = "payment_accounts",
  PROFILES = "profiles",
  USERS = "users",
  USER_TOKENS = "user_tokens",
}

export enum ENVIRONMENT_VARIABLES {
  NODE_ENV = "NODE_ENV",

  // Server Keys
  APP_TITLE = "APP_TITLE",
  PORT = "PORT",
  BASE_URL = "BASE_URL",
  MONGO_URI = "MONGO_URI",
  JWT_SECRET = "JWT_SECRET",
  API_KEY = "API_KEY",
  POSTMAN_URL = "POSTMAN_URL",
  DOCS_USERNAME = "DOCS_USERNAME",
  DOCS_PASSWORD = "DOCS_PASSWORD",
  SUPPORT_EMAIL = "SUPPORT_EMAIL",

  // Twilio Keys
  TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID",
  TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN",

  // Braintree Keys
  BRAINTREE_MERCHANT_ID = "BRAINTREE_MERCHANT_ID",
  BRAINTREE_PUBLIC_KEY = "BRAINTREE_PUBLIC_KEY",
  BRAINTREE_PRIVATE_KEY = "BRAINTREE_PRIVATE_KEY",

  // Stripe Keys
  STRIPE_SECRET_KEY = "STRIPE_SECRET_KEY",
  STRIPE_PUBLISHABLE_KEY = "STRIPE_PUBLISHABLE_KEY",
  STRIPE_ENDPOINT_SECRET = "STRIPE_ENDPOINT_SECRET",

  // Google Keys
  GOOGLE_EMAIL = "GOOGLE_EMAIL",
  GOOGLE_APP_PASSWORD = "GOOGLE_APP_PASSWORD",
  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
  GOOGLE_REDIRECT_URI = "GOOGLE_REDIRECT_URI",
  GOOGLE_REFRESH_TOKEN = "GOOGLE_REFRESH_TOKEN",

  // Facebook Keys
  FACEBOOK_CLIENT_ID = "FACEBOOK_CLIENT_ID",
  FACEBOOK_CLIENT_SECRET = "FACEBOOK_CLIENT_SECRET",
  FACEBOOK_REDIRECT_URI = "FACEBOOK_REDIRECT_URI",

  // Apple Keys
  APPLE_CLIENT_ID = "APPLE_CLIENT_ID",
  APPLE_TEAM_ID = "APPLE_TEAM_ID",
  APPLE_KEY_ID = "APPLE_KEY_ID",
  APPLE_REDIRECT_URI = "APPLE_REDIRECT_URI",
  APPLE_PRIVATE_KEY = "APPLE_PRIVATE_KEY",

  // AWS Keys
  AWS_BUCKET_NAME = "AWS_BUCKET_NAME",
  AWS_ACCESS_KEY = "AWS_ACCESS_KEY",
  AWS_SECRET_KEY = "AWS_SECRET_KEY",
  AWS_REGION = "AWS_REGION",
  S3_URL = "S3_URL",
  CDN_URL = "CDN_URL",

  // AWS IoT Core Configuration
  AWS_IOT_ENDPOINT = "AWS_IOT_ENDPOINT",

  // AWS Certificate paths
  AWS_IOT_CERT_PATH = "AWS_IOT_CERT_PATH",
  AWS_IOT_PRIVATE_KEY_PATH = "AWS_IOT_PRIVATE_KEY_PATH",
  AWS_IOT_CA_PATH = "AWS_IOT_CA_PATH",

  // AWS MQTT Configuration
  MQTT_CLIENT_ID = "MQTT_CLIENT_ID",
  MQTT_KEEP_ALIVE = "MQTT_KEEP_ALIVE",
  // AWS Topic Configuration
  DEVICE_TELEMETRY_TOPIC = "DEVICE_TELEMETRY_TOPIC",
  DEVICE_COMMAND_TOPIC = "DEVICE_COMMAND_TOPIC",

  // Plaid Keys
  PLAID_CLIENT_ID = "PLAID_CLIENT_ID",
  PLAID_SECRET = "PLAID_SECRET",

  // Sumsub Keys
  SUMSUB_APP_TOKEN = "SUMSUB_APP_TOKEN",
  SUMSUB_SECRET_KEY = "SUMSUB_SECRET_KEY",
  SUMSUB_BASE_URL = "SUMSUB_BASE_URL",

  // Agora Keys
  AGORA_APP_ID = "AGORA_APP_ID",
  AGORA_APP_CERTIFICATE = "AGORA_APP_CERTIFICATE",

  // SendGrid Keys
  SEND_GRID_API_KEY = "SEND_GRID_API_KEY",

  // Tap Keys
  TAP_SECRET_KEY = "TAP_SECRET_KEY",
  TAP_WEBHOOK_SECRET = "TAP_WEBHOOK_SECRET",

  // App URLs
  LOCAL_3000 = "LOCAL_3000",
  ADMIN_PANEL_URL = "ADMIN_PANEL_URL",
  WEB_APP_URL = "WEB_APP_URL",
  PIE_HOST_URL = "PIE_HOST_URL",
}

export enum USER_TYPES {
  STANDARD = "standard",
  GUEST = "guest",
}

export enum ADMIN_TYPES {
  STANDARD = "standard",
  SUPER_ADMIN = "super_admin",
}

export enum ACCOUNT_TYPES {
  USER = "user",
  ADMIN = "admin",
}

export enum GEO_JSON_TYPES {
  POINT = "Point",
  LINESTRING = "LineString",
  POLYGON = "Polygon",
  MULTIPOINT = "MultiPoint",
  MULTILINESTRING = "MultiLineString",
  MULTIPOLYGON = "MultiPolygon",
}

export enum PAYMENT_ACCOUNT_TYPES {
  BRAINTREE = "braintree",
  STRIPE_CUSTOMER = "stripe_customer",
  STRIPE_ACCOUNT = "stripe_account",
}

export enum NOTIFICATION_TYPES {
  NEW_MESSAGE = "new_message",
}

export enum ACCOUNT_STATUSES {
  ACTIVE = "active",
  INACTIVE = "inactive",
}

export enum CONVERSATION_STATUSES {
  PENDING = "pending",
  ACCEPTED = "accepted",
  REJECTED = "rejected",
}

export enum MESSAGE_STATUSES {
  UNREAD = "unread",
  READ = "read",
}

export enum NOTIFICATION_STATUSES {
  UNREAD = "unread",
  READ = "read",
}

export enum SOCKET_EVENTS {
  NEW_MESSAGE_ = "new_message_",
  CONVERSATIONS_UPDATED = "conversations_updated",
}
